# Generated by Django 3.1.7 on 2021-03-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPln',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=256, verbose_name='Asset')),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=64)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('buy', 'kup'), ('sell', 'sprzedaj')], max_length=16)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('cash', 'gotówka'), ('stock', 'akcje'), ('bond', 'obligacje'), ('crypto', 'krypto'), ('commodity', 'surowce')], max_length=16)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountant.asset')),
            ],
        ),
    ]
