# Generated by Django 3.1.7 on 2021-03-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_accountpln_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpln',
            name='total_balance',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountpln',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'wpłata'), ('withdraw', 'wypłata')], max_length=8),
        ),
    ]
